#!/bin/bash

echo "═══════════════════════════════════════════════════════════════"
echo "  MySQL Conflict Resolution Script"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "You have TWO MySQL installations running:"
echo "  1. System MySQL: /usr/local/mysql (RUNNING on port 3306)"
echo "  2. Homebrew MySQL: /opt/homebrew/opt/mysql (CAN'T START)"
echo ""
echo "Choose an option:"
echo ""
echo "OPTION 1: Use System MySQL (Already Running)"
echo "  → We'll reset the root password for this MySQL"
echo ""
echo "OPTION 2: Stop System MySQL, Use Homebrew MySQL"
echo "  → Requires sudo to stop system MySQL"
echo ""
read -p "Enter choice (1 or 2): " choice

if [ "$choice" == "1" ]; then
    echo ""
    echo "Resetting System MySQL root password..."
    echo "You'll need to run these commands manually:"
    echo ""
    echo "1. Stop system MySQL:"
    echo "   sudo launchctl unload -w /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist"
    echo "   OR: sudo /usr/local/mysql/support-files/mysql.server stop"
    echo ""
    echo "2. Start in safe mode:"
    echo "   sudo /usr/local/mysql/bin/mysqld_safe --skip-grant-tables --skip-networking &"
    echo ""
    echo "3. Wait 3 seconds, then connect:"
    echo "   /usr/local/mysql/bin/mysql -u root"
    echo ""
    echo "4. Reset password:"
    echo "   FLUSH PRIVILEGES;"
    echo "   ALTER USER 'root'@'localhost' IDENTIFIED BY 'your_new_password';"
    echo "   FLUSH PRIVILEGES;"
    echo "   EXIT;"
    echo ""
    echo "5. Stop safe mode and restart:"
    echo "   sudo /usr/local/mysql/support-files/mysql.server stop"
    echo "   sudo /usr/local/mysql/support-files/mysql.server start"
    
elif [ "$choice" == "2" ]; then
    echo ""
    echo "Stopping System MySQL and starting Homebrew MySQL..."
    echo "Run these commands:"
    echo ""
    echo "1. Stop system MySQL (requires sudo):"
    echo "   sudo launchctl unload -w /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist"
    echo ""
    echo "2. Start Homebrew MySQL:"
    echo "   brew services start mysql"
    echo ""
    echo "3. Reset Homebrew MySQL root password (if needed):"
    echo "   Follow the password reset steps for Homebrew MySQL"
else
    echo "Invalid choice"
fi

